version: "3.4"

services:

  # haproxy:
  #   build: ./haproxy
  #   image: haproxy_manh
  #   container_name: haproxy_manh
  #   ports:
  #     - "8081:80"

  # Define your individual services
  flask:
    # Build the flask service using the docker file in "flask" directory
    build: ./flask
    image: fask_manh
    # Give our flask container a friendly name
    container_name: flask_manh

    restart: always
    environment: 
      - APP_NAME=MyFlaskApp
    ports:
      - "8080:8080"
    sysctls:
      - net.core.somaxconn=4096  
  
  nginx:
    build: ./nginx
    container_name: nginx_manh_py_uwsgi
    image: nginx_manh
    restart: always
    ports: 
     - "8000:80"