version: "3.4"

services:

  # Define your individual services
  flask:
    # Build the flask service using the docker file in "flask" directory
    build: ./flask
    image: fask_manh
    # Give our flask container a friendly name
    container_name: flask_manh

    restart: always
    environment: 
      - APP_NAME=MyFlaskApp
    expose: 
    - 8080
  
  nginx:
    build: ./nginx
    container_name: nginx_manh
    image: nginx_manh
    restart: always
    ports: 
     - "80:80"